### ISSUE TITLE
My logs were reset

### ISSUE THREAD

**Issue by Blondeyfox** [TheStonedTurtle/Loot-Logger#11]
I've been using this plugin for a month or more and I guess at some point in the last week it reset and I have no data tracked from before the week. Would that data have been overridden locally or would I be able to find it?

**Comment by Blondeyfox** [comment]
You know what, I have changed my username since then, perhaps that caused the issue. Would I be able to edit the local files to accept my new username?

**Comment by TheStonedTurtle** [comment]
Yeah this plugin ties data to your username instead of your login name. You
should be able to rename the folder in `~/.runelite/loots/`, if youve
killed stuff since your name change you will need to manually combine the
files, ensuring the file ends with a blank line.

At some point i will convert to login names and auto convert existing data.

**Comment by Blondeyfox** [comment]
Just dumped all the texts into the new folder and its working gewd! thank you sir
