### ISSUE TITLE
Missing bosses

### ISSUE THREAD

**Issue by SAwesome1018** [TheStonedTurtle/Loot-Logger#40]
are there any plans to add a "tile" for new(ish) bosses? such as hespori, guardians of the rift, Tombs of amascut, etc?

**Comment by TheStonedTurtle** [comment]
I decided against adding Hespori because it's not really a boss, same thing for most slayer monsters that have uniques like demonic gorillas, basilisk knights, etc

I also didn't add the Guardians of the Rift tab because I wouldn't be able to easily track all of the items bought from the store.

I already have a PR out for Tombs of Amascut tab.
