### ISSUE TITLE
Loot being saved under a folder name that's just a string of numbers rather than username

### ISSUE THREAD

**Issue by connylite** [TheStonedTurtle/Loot-Logger#42]
Loots are being logged properly, just under the wrong folder. 
I restarted the client, issue persists.

**Comment by connylite** [comment]
ok i see that you changed folders to be a hash of the account. won't that displace everyones loot they've been storing for a while? i transferred my own files over but some people are going to end up losing data.

**Comment by TheStonedTurtle** [comment]
> ok i see that you changed folders to be a hash of the account. won't that displace everyones loot they've been storing for a while? i transferred my own files over but some people are going to end up losing data.

The folder should automatically be renamed when you load the game with RuneLite (not through the Jagex Launcher).

The only reason why it wouldn't rename your existing folder is because a folder with your account hash already exists, which would happen if you launched RuneLite through the Jagex launcher.

I can't rename your folder when launched through the Jagex launcher as RuneLite can't access your account's login name when ran through the Jagex launcher, which is why I made this change in the first place.
