### ISSUE TITLE
Implement the functionality of setting splits for logged items

### ISSUE THREAD

**Issue by Nixsm** [TheStonedTurtle/Loot-Logger#48]
First of all! Love the plugin, I use it constantly and it makes my overall OSRS experience much better, so thanks for that!

If you raid in team and split loots, the log will have a invalid value, as you didn't get the whole split for that one raid loot, it would be great to set splits for items, so we can have a more accurate total log money.

This would also add the ability to set the value you got the item when you got it, as in, my team and I got a Lightbearer close to release on a 5-man raid, the split was 12m-each. Yesterday we had another one in a 4-man, the split was 5m.

Maybe I'm requesting this in the wrong plugin, as it requires Loot Logger to be enabled.

How complex would such feature be to implement?

**Comment by TheStonedTurtle** [comment]
I believe this feature to be outside the scope of this plugin as this plugin is just meant to log the loot your receive to your local hard drive instead of relying on the RuneLite servers to persist your data.

RuneLite has started to store your loot data for longer, but when this plugin was originally created data was deleted after 30days of you last killing that NPC.

I would recommend the `Raid Tracker` plugin but it doesn't seem to have been updated for toa.
