### ISSUE TITLE
Disconnect/freeze when new drop is received

### ISSUE THREAD

**Issue by MaxedWhip** [TheStonedTurtle/Loot-Logger#49]
At cerberus specifically, nowhere else, the client has been getting frozen or disconnected for approx 0,2 seconds every kill the moment loot should have appeared. Turning off loot logger removes the issue and turning the plugin back on the issue resumes. At the same time It does not let me open cerberus log anymore, though all other logs can be opened through the side panel as normal. Is it possible the problem is caused by too many kills logged? At the moment theres around 20k kills logged in cerberus.

**Comment by TheStonedTurtle** [comment]
There's a very rare issue where instead of a new entry being inserted on a new line it is appended to the previous line with a bunch of spaces between it. This can cause the reader to fail.

If you want to upload your cerb log here I can take a look.

Also if you can attach your `client.log` file from `.runelite/logs` that would help as well.

**Comment by MaxedWhip** [comment]
[cerberus.log](https://github.com/TheStonedTurtle/Loot-Logger/files/9787206/cerberus.log)
[client.log](https://github.com/TheStonedTurtle/Loot-Logger/files/9787252/client.log)
Looks like 27157-27160 kc theres 1 entry like that atleast?

**Comment by TheStonedTurtle** [comment]
[cerberus.log](https://github.com/TheStonedTurtle/Loot-Logger/files/9789349/cerberus.log)
I fixed that issue where you mentioned and it's loading fine for me now, let me know if it still causes the lag spike for you.

**Comment by MaxedWhip** [comment]
Looks like that did it, thanks!
