### ISSUE TITLE
Araxxor logging shows items not dropped from boss

### ISSUE THREAD

**Issue by Brasolis** [TheStonedTurtle/Loot-Logger#67]
The plugin is showing my abyssal bludgeon as a drop from araxxor for some reason.

![21-10-2024 - (681)](https://github.com/user-attachments/assets/ec7b9b45-4a88-4753-8d69-e91f2e4edb99)

**Comment by TheStonedTurtle** [comment]
All of the loot data (except for pets) comes from the RL `Loot Tracker` plugin, this plugin just persists the data locally to `.log` files under `.runelite/loots` and provides the Sidebar UI for viewing it.

You should report this to the RL team, but I'm pretty sure this is unavoidable due to the way loot from Araxxor is received.

You can however find the `araxxor.log` file under `.runelite/loots/<account-hast>/npcs/`, edit the file, and remove the bludgeon entry from the log, but you will need to make sure you remove it properly.

<details><summary>Here's an explainer of how to remove an item from the log</summary>
<p>

**You should first make a copy of the file you are editing just in case you mess up.**

Lets take this line from my log as an example:
```json
{"name":"Araxxor","level":-1,"killCount":228,"type":"NPC","drops":[{"name":"Wild pie","id":7208,"quantity":2,"price":733},{"name":"Prayer potion(2)","id":141,"quantity":2,"price":5150},{"name":"Super combat potion(1)","id":12701,"quantity":1,"price":4123}],"date":"Sep 2, 2024, 1:52:46 AM"}
```
The important part here is the stuff between the opening and closing square brackets after `drops` (`[` and `]`)

```json
"drops":[{"name":"Wild pie","id":7208,"quantity":2,"price":733},{"name":"Super combat potion(1)","id":12701,"quantity":1,"price":4123},{"name":"Prayer potion(2)","id":141,"quantity":2,"price":5150}]
```

In order to remove the `Super Combat (1)` I'd need to remove:
```json
{"name":"Super combat potion(1)","id":12701,"quantity":1,"price":4123},
```
Note the trailing comma `,` at the end, that needs to be removed. If this was the last item, such as `Prayer Potion(2)` then we'd need to remove the comma before the entry.

Each entry in that list needs to be separated by a comma but there can't be duplicate or missing commas.
So `[{1},{2},{3}]` is valid but `[{1},,{3}]` and `[{1}{3}]` are both invalid

You can use this tool to validate the entire line after you make the changes. https://jsonlines.org/validator/


So after removing the entry the `drops` array would look like this
```json
"drops":[{"name":"Wild pie","id":7208,"quantity":2,"price":733},{"name":"Prayer potion(2)","id":141,"quantity":2,"price":5150}]
```

And the entire line would look like this:
```json
{"name":"Araxxor","level":-1,"killCount":228,"type":"NPC","drops":[{"name":"Wild pie","id":7208,"quantity":2,"price":733},{"name":"Prayer potion(2)","id":141,"quantity":2,"price":5150}],"date":"Sep 2, 2024, 1:52:46 AM"}
```

You can now save this file and then either click the refresh button or re-navigate to that loot view and it should load your changes.

</p>
</details>

**Comment by Brasolis** [comment]
Thank you very much for the detailed response. I edited the log as you suggested. 

Sorry for the wrong issue!
